//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_VacationLeave
    {
        public System.Guid ID_VacationLeave { get; set; }
        public System.Guid ID_User { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
    }
}
